title: "GAN Vocoder :<br>Multi-Resolution Discriminator Is All You Need"
description: "Authors : Jaeseong You, Dalhyun Kim, Gyuhyeon Nam, Geumbyeol Hwang, Gyeongsu Chae<br>ArXiv: <a href='https://arxiv.org/abs/2102.08075'>arXiv:2102.08075</a>"
show_downloads: true
google_analytics:
theme: jekyll-theme-architect