title: "GAN Vocoder: <br>Multi-Resolution Discriminator Is All You Need"
description: "Authors: Jaeseong You, Dalhyun Kim, Gyuhyeon Nam, Geumbyeol Hwang, Gyeongsu Chae<br>ArXiv: <a href='https://arxiv.org/abs/2103.05236'>arXiv:2103.05236</a>"
show_downloads: true
google_analytics:
theme: jekyll-theme-architect